# Generated by Django 4.2.23 on 2025-08-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='inprogress',
            field=models.BooleanField(default=False),
        ),
    ]
