# Generated by Django 4.2.23 on 2025-08-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_inprogress'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='todo',
            constraint=models.CheckConstraint(check=models.Q(('inprogress', True), ('completed', True), _negated=True), name='todo_not_both_true'),
        ),
    ]
